name: Remet
options:
  bundleIdPrefix: com.remet
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"

targets:
  Remet:
    type: application
    platform: iOS
    scheme:
      testTargets:
        - RemetTests
    sources:
      - path: Remet
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.remet.app
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "Remet needs access to your photos to identify people."
        INFOPLIST_KEY_NSCameraUsageDescription: "Remet needs camera access to capture photos for face identification."
        INFOPLIST_KEY_NSPhotoLibraryAddUsageDescription: "Remet can save processed photos to your library."
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        ENABLE_PREVIEWS: YES
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
    info:
      path: Remet/Info.plist
      properties:
        UILaunchScreen: {}
        NSPhotoLibraryUsageDescription: "Remet needs access to your photos to identify people."
        NSCameraUsageDescription: "Remet needs camera access to capture photos for face identification."
        NSPhotoLibraryAddUsageDescription: "Remet can save processed photos to your library."
        NSContactsUsageDescription: "Remet can link people to your contacts and optionally update contact photos."
        NSLocationWhenInUseUsageDescription: "Remet uses your location to record where you met people."
        CFBundleDisplayName: "Remet"
        ITSAppUsesNonExemptEncryption: false
        CFBundleURLTypes:
          - CFBundleURLName: "com.remet.app"
            CFBundleURLSchemes:
              - "remet"
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleShortVersionString: "1.1.1"
        CFBundleLocalizations:
          - en
          - zh-Hans
          - zh-Hant
          - ja
        UIBackgroundModes:
          - remote-notification
    dependencies:
      - target: ShareExtension
    entitlements:
      path: Remet/Remet.entitlements
      properties:
        aps-environment: development
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.remet.Remet
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.security.application-groups:
          - group.com.remet.shared

  RemetTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: RemetTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: Remet
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.remet.app.tests
        GENERATE_INFOPLIST_FILE: YES

  ShareExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: ShareExtension
        excludes:
          - "**/.DS_Store"
    info:
      path: ShareExtension/Info.plist
      properties:
        CFBundleDisplayName: "Remet"
        CFBundleShortVersionString: "1.1.1"
        NSExtension:
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsImageWithMaxCount: 10
          NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).ShareViewController"
          NSExtensionPointIdentifier: "com.apple.share-services"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.remet.app.share
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        SKIP_INSTALL: YES
    entitlements:
      path: ShareExtension/ShareExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.remet.shared
